### ISSUE TITLE
luarocks install xsys fails on Lua 5.4.3

### ISSUE THREAD

**Issue by gganapat** [stepelu/lua-xsys#4]
Hi, how do I get past this error? SciLua apparently needs xys which doesn't build for 5.4.3. I would appreciate your help.
Thanks!

--------------------------

luarocks install xsys
Warning: falling back to curl - install luasec to get native HTTPS support

Error: No results matching query were found for Lua 5.4.
To check if it is available for other Lua versions, use --check-lua-versions.
Ganis-MacBook-Pro:~ gani$ luarocks install xsys --check-lua-versions
Warning: falling back to curl - install luasec to get native HTTPS support
xsys not found for Lua 5.4.
Checking if available for other Lua versions...
Checking for Lua 5.1...
Checking for Lua 5.2...
Checking for Lua 5.3...

Error: No results matching query were found for Lua 5.4.
xsys supports only Lua 5.1 and Lua 5.2 and Lua 5.3 but not Lua 5.4.

**Comment by stepelu** [comment]
SciLua is only compatible with LuaJIT, which targets Lua 5.1 (with extensions).
xsys could be checked for compatibility and updated, but SciLua will not work anyway on plain Lua.

**Comment by gganapat** [comment]
Thanks!

G-
